import type { Metadata } from "next";
import { Inter, Noto_Sans_JP } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Denpalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>{children}</div>
        <nav>
          <ul>
            <li>
              <a>
                <button>Main</button>
              </a>
            </li>
            <li>
              <a>
                <button>Search</button>
              </a>
            </li>
          </ul>
        </nav>
      </body>
    </html>
  );
}
